# Generated by Django 5.2.11 on 2026-02-16 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcription', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='sample_rate',
            field=models.IntegerField(choices=[(8000, '8000 Hz'), (16000, '16000 Hz'), (22050, '22050 Hz'), (44100, '44100 Hz'), (48000, '48000 Hz')], default=44100, help_text='Sample rate in Hz'),
        ),
    ]
