# Generated by Django 5.2.11 on 2026-02-16 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcription', '0002_alter_project_sample_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='folder_path',
            field=models.CharField(default='.', help_text='Select a folder containing audio files', max_length=255),
        ),
    ]
