# Generated by Django 5.2.11 on 2026-02-16 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcription', '0004_alter_project_folder_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='folder_path',
            field=models.CharField(default='./', help_text='Select a folder to save audio files', max_length=255),
        ),
    ]
