# Generated by Django 5.2.11 on 2026-02-16 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcription', '0005_alter_project_folder_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='folder_path',
            field=models.CharField(default='./', help_text='Select a base folder. Subfolders for the project and audio will be created automatically.', max_length=255),
        ),
    ]
