# Generated by Django 5.2.11 on 2026-02-17 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcription', '0007_alter_project_folder_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcript',
            name='audio_file',
            field=models.CharField(max_length=255),
        ),
    ]
