# Generated by Django 5.2.11 on 2026-03-03 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcription', '0008_alter_transcript_audio_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='total_duration',
            field=models.FloatField(default=0.0, help_text='Total audio duration in seconds'),
        ),
    ]
